INSERT INTO SERIES (NOMBRE, FECHA_ESTRENO, TEMATICA, DIRECTOR, RATING, IDIOMA, ESTADO, CADENA)
VALUES ('Breaking Bad', '2008-01-20', 'Drama', 'Vince Gilligan', 9, 'English', 'TERMINADA', 'AMC');

INSERT INTO SERIES (NOMBRE, FECHA_ESTRENO, TEMATICA, DIRECTOR, RATING, IDIOMA, ESTADO, CADENA)
VALUES ('Stranger Things', '2016-07-15', 'Sci-Fi', 'The Duffer Brothers', 8, 'English', 'TERMINADA', 'Netflix');

INSERT INTO SERIES (NOMBRE, FECHA_ESTRENO, TEMATICA, DIRECTOR, RATING, IDIOMA, ESTADO, CADENA)
VALUES ('La Casa de Papel', '2017-05-02', 'Crime', 'Álex Pina', 8, 'Spanish', 'EN EMISION', 'Antena 3');