-- BBDD LOGIN --
CREATE DATABASE IF NOT EXISTS LOGIN;
USE LOGIN;

-- TABLA LOGINS --
DROP TABLE IF EXISTS LOGINS;
CREATE TABLE IF NOT EXISTS LOGINS(
    USUARIO VARCHAR(50) NOT NULL,
    PASSWD VARCHAR(100) NOT NULL
    );

-- BBDD APP --

CREATE DATABASE IF NOT EXISTS APP_SERIES;
USE APP_SERIES;

-- TABLA SERIES --
DROP TABLE IF EXISTS SERIES;
CREATE TABLE IF NOT EXISTS SERIES(
    ID INT AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    FECHA_ESTRENO DATE NOT NULL,
    TEMATICA VARCHAR(150) NOT NULL,
    DIRECTOR VARCHAR(50) NOT NULL,
    RATING INT,
    IDIOMA VARCHAR(50),
    ESTADO ENUM("TERMINADA","EN EMISION"),
    CADENA VARCHAR(50),
    PRIMARY KEY(ID)
    );

-- TABLA EPISODIOS --
DROP TABLE IF EXISTS EPISODIOS;
CREATE TABLE IF NOT EXISTS EPISODIOS(
    ID INT AUTO_INCREMENT NOT NULL,
    NUMERO INT NOT NULL,
    TEMPORADA INT NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    SERIE INT NOT NULL,
    FECHA_SALIDA DATE NOT NULL,
    DURACION TIME NOT NULL,
    FOREIGN KEY (SERIE) REFERENCES SERIES(ID),
    PRIMARY KEY(ID)
    );